### ISSUE TITLE
Undefined method setManagerType on admin class

### ISSUE THREAD

**Issue by aserratorta** [aserratorta/lotto#1]
I want to render the LottoNumberAdmin, but it shows me this error:

![image](https://cloud.githubusercontent.com/assets/12971681/12369617/582148f4-bbfb-11e5-8fcb-3177d2d31cb9.png)

And I don't know what's the cause.

**Comment by davidromani** [comment]
Your LottoNumberAdmin class must extends from Sonata Admin class. Check carefully other project examples and **always** read the official documentation before.

<img width="811" alt="captura de pantalla 2016-01-17 a les 12 43 18" src="https://cloud.githubusercontent.com/assets/698779/12377275/2ba3f790-bd18-11e5-94b8-dc664f02662e.png">

**Comment by aserratorta** [comment]
:thumbsup:
I'll explane to you why I was confused.
